// AngularTasklist/src/app/task-update/task-update.component.ts
import { Component, OnInit } from '@angular/core';
import { TaskService } from '../shared/task-service';
import { Router } from '@angular/router';
import { UserService } from '../shared/user-service';
import { Task } from '../entities/task';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
	selector: 'app-task-update',
	template: `
		<h1>Create a task</h1>

		<form [formGroup]="taskForm" (ngSubmit)="handleSubmit()">
			<div>
				<label for="title">Title</label>
				<input type="text" id="title" formControlName="title" />
			</div>
			<div>
				<label for="assigneeId">Assignee</label>
				<select id="assigneeId" formControlName="assigneeId">
					<option value="">None</option>
					<option *ngFor="let user of userService.getAll()|async" [value]="user.id">{{user.name}}</option>
				</select>
			</div>
			<input type="submit" />
		</form>
	`
})
export class TaskUpdateComponent {
	public taskForm: FormGroup;

	constructor(private taskService: TaskService, private userService: UserService, private router: Router, formBuilder: FormBuilder) {
		this.taskForm = formBuilder.group({
			assigneeId: '',
			title: ''
		});
	}

	public handleSubmit(): void {
		const formControls = this.taskForm.controls;
		this.taskService.addTask({
			assigneeId: formControls.assigneeId.value ? +formControls.assigneeId.value : null,
			title: formControls.title.value,
			completed: false
		});
		this.router.navigateByUrl('/').catch(error => console.log(`Errors while navigating : ${error}`));
	}

}

<p>task-update works!</p>

// SvelteTaskList/src/components/TaskUpdate.svelte
<script>
	import { taskStore } from '../stores/task-store';
	import { userStore } from '../stores/user-store';
	import { push } from 'svelte-spa-router';
	import { Task } from '../entities/task';

	function handleSubmit() {
		taskStore.addTask(task);
		push('/');
	}

	let task = new Task();
</script>

<h1>Create a task</h1>

<form on:submit|preventDefault={handleSubmit}>
	<div>
		<label for="name">Title</label>
		<input type="text" id="name" bind:value={task.title} />
	</div>
	<div>
		<label for="assigneeId">Assignee</label>
		<select id="assigneeId" bind:value={task.assigneeId}>
			<option value="">None</option>
			{#each $userStore as user}
				<option value={user.id}>{user.name}</option>
			{/each}
		</select>
	</div>
	<input type="submit" />
</form>
